- name: install mariadb and configure
  hosts: all
  #remote_user: wsg
  #sudo: yes
  #sudo_user: root
  gather_facts: false
  
  tasks:
  - name: test command pwd
    sudo: yes
    shell: pwd

  - name: apt key 
    apt_key: url=http://nginx.org/keys/nginx_signing.key state=present 

#    - name: apt repsoitory 
#      apt_repository: repo='deb deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx' state=present filename='nginx' update_cache='yes'
#    - name: isntall  
#        apt: name='nginx' state='present' update_cache='yes'

